<a href="https://colab.research.google.com/github/HajjoujiProf/Linear-Regression-Stock-Price/blob/main/Linear_Regression_Stock_Price.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression


x = np.array([1, 2, 3, 4, 5]).reshape((-1, 1))
y = np.array([5, 7, 9, 11, 12])

print(x)
print(y)

[[1]
 [2]
 [3]
 [4]
 [5]]
[ 5  7  9 11 12]


In [ ]:
# a) Build a regression equation for stock price Y over time X: Y=aX+b+e.

In [ ]:
model = LinearRegression()
model.fit(x, y)
model = LinearRegression().fit(x, y)



In [ ]:
y_pred = model.intercept_ + model.coef_ * x
print('predicted response:', y_pred, sep='\n')

predicted response:
[[ 5.2]
 [ 7. ]
 [ 8.8]
 [10.6]
 [12.4]]


In [ ]:
# b) Calculate the coefficient of determination

In [ ]:
r_sq = model.score(x, y)
print('coefficient of determination is :', r_sq)

coefficient of determination is : 0.9878048780487805


In [ ]:
# c) Give a forecast of the stock price at time X=6

In [ ]:
new_x = np.array([1, 2, 3, 4, 5,6]).reshape((-1, 1))
new_y = np.array([5, 7, 9, 11, 12,14])

print(new_x)
print(new_y)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[ 5  7  9 11 12 14]


In [ ]:
model = LinearRegression()
model.fit(new_x, new_y)
model = LinearRegression().fit(new_x, new_y)

In [ ]:
new_y_pred = model.intercept_ + model.coef_ * x
print('predicted response of Forecast :', new_y_pred, sep='\n')

predicted response:
[[ 5.23809524]
 [ 7.00952381]
 [ 8.78095238]
 [10.55238095]
 [12.32380952]
 [14.0952381 ]]


In [ ]:
import numpy as np
>>> from sklearn.linear_model import LinearRegression

>>> x = [
...   [0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]
... ]
>>> y = [4, 5, 20, 14, 32, 22, 38, 43]
>>> x, y = np.array(x), np.array(y)